### ISSUE TITLE
[PE-D][Tester F] Invalid view command /view TIMETABLESE in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W13-2/tp#123]
Entering the following command 

/view TIMETABLESE

provided in "Example Input" results in the following message

Error! Invalid view command. Please follow the command format provided

The command can be seen in the link below:

https://ay2223s1-cs2113-w13-2.github.io/tp/UserGuide.html#view-command-for-all-timetables-created-by-user-view-timetables

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: xzynos/ped#1

**Comment by wangtingjia** [comment]
Bug Resolved
