### ISSUE TITLE
[PE-D][Tester E] Store favourite, exit and reload, then file invalid

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W13-2/tp#167]
local Data file wasnt tampered with

![Screen Shot 2022-10-28 at 17.52.18.png](https://raw.githubusercontent.com/pipipipi2002/ped/main/files/63f73143-fca1-41c7-9e45-403019dcd360.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: pipipipi2002/ped#17

**Comment by wangtingjia** [comment]
Resolved
